### ISSUE TITLE
webRTC

### ISSUE THREAD

**Issue by iOSHyDev** [stevegraham/twilio_client_phonegap#11]
Hey,
I just researched or found that iOS mobile devices not supported webRTC.
So, will this code work for me?

Thanks.

**Comment by stevegraham** [comment]
Yes

**Comment by iOSHyDev** [comment]
Thanks for your reply. After all done, when I build the code for iOS, I am getting  error in xcode like (Command /bin/sh failed with exit code 3 ) :

**rsync: opendir "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/cordova-js-src" failed: Permission denied (13)
rsync: opendir "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/css" failed: Permission denied (13)
rsync: opendir "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/img" failed: Permission denied (13)
rsync: opendir "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/js" failed: Permission denied (13)
rsync: opendir "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/lib" failed: Permission denied (13)
rsync: send_files failed to open "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/cordova.js": Permission denied (13)
rsync: send_files failed to open "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/cordova_plugins.js": Permission denied (13)
rsync: send_files failed to open "/Users/ios/Documents/ionic Project Apps/pushMyApp/platforms/ios/www/index.html": Permission denied (13)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Error occured on copying www. Code: 23
Command /bin/sh failed with exit code 3**

**Comment by stevegraham** [comment]
This doesn't look like an issue with this library. Unable to help you with this. Sorry.

**Comment by iOSHyDev** [comment]
Thanks ! The code works for me.. 👍

**Comment by iOSHyDev** [comment]
Hi Stevie,

Can we change toCall parameter with my own parameter?

Thanks,
Pooja
